version: '3.4'

services:
  yolo:
    build: ./
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      #to the host
      - 8005:8000 #host:container
    stdin_open: true
    tty: true
    ulimits:
      memlock: -1 # set upper limit for how much memory is locked for the container (-1 means lock as much as the container uses)
    shm_size: 4gb

    command: uvicorn main:api --host 0.0.0.0
